//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Department.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HR_DepartmentEntities1 : DbContext
    {


        private static HR_DepartmentEntities1 _context;

        public static HR_DepartmentEntities1 GetContext()
        {
            if (_context == null)
                _context = new HR_DepartmentEntities1();
            return _context;
        }

        public HR_DepartmentEntities1()
            : base("name=HR_DepartmentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<companyBD> companyBD { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<teams> teams { get; set; }
        public virtual DbSet<vacancy> vacancy { get; set; }
    }
}
